version: '2'
services:
  hello:
    image: registry.cn-hangzhou.aliyuncs.com/jingshanlb/openresty-helloworld
    restart: always
    labels:
      aliyun.routing.port_8080: http://apisvc/api
      aliyun.scale: "2"
